export const bedsData = [
  {
    "id": 1,
    "bed_number": "GWA-01",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "occupied",
    "patient_id": 1,
    "patient_name": "Ahmad Hassan",
    "bed_type": "general"
  },
  {
    "id": 2,
    "bed_number": "GWA-02",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "occupied",
    "patient_id": 2,
    "patient_name": "Sara Khan",
    "bed_type": "general"
  },
  {
    "id": 3,
    "bed_number": "GWA-03",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "occupied",
    "patient_id": 3,
    "patient_name": "Muhammad Ali",
    "bed_type": "general"
  },
  {
    "id": 4,
    "bed_number": "GWA-04",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "reserved",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 5,
    "bed_number": "GWA-05",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 6,
    "bed_number": "GWA-06",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 7,
    "bed_number": "GWA-07",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 8,
    "bed_number": "GWA-08",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "cleaning",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 9,
    "bed_number": "GWA-09",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 10,
    "bed_number": "GWA-10",
    "ward": "General Ward A",
    "ward_id": 1,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 11,
    "bed_number": "ICU-01",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "occupied",
    "patient_id": 5,
    "patient_name": "Khalid Rehman",
    "bed_type": "ICU"
  },
  {
    "id": 12,
    "bed_number": "ICU-02",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "occupied",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "ICU"
  },
  {
    "id": 13,
    "bed_number": "ICU-03",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "ICU"
  },
  {
    "id": 14,
    "bed_number": "ICU-04",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "ICU"
  },
  {
    "id": 15,
    "bed_number": "ICU-05",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "reserved",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "ICU"
  },
  {
    "id": 16,
    "bed_number": "ICU-06",
    "ward": "ICU",
    "ward_id": 2,
    "floor": "Ground",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "ICU"
  },
  {
    "id": 17,
    "bed_number": "CAR-01",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "occupied",
    "patient_id": 5,
    "patient_name": "Khalid Rehman",
    "bed_type": "general"
  },
  {
    "id": 18,
    "bed_number": "CAR-02",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 19,
    "bed_number": "CAR-03",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 20,
    "bed_number": "CAR-04",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "reserved",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 21,
    "bed_number": "CAR-05",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 22,
    "bed_number": "CAR-06",
    "ward": "Cardiology",
    "ward_id": 3,
    "floor": "First",
    "status": "occupied",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 23,
    "bed_number": "ORT-01",
    "ward": "Orthopedics",
    "ward_id": 4,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 24,
    "bed_number": "ORT-02",
    "ward": "Orthopedics",
    "ward_id": 4,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 25,
    "bed_number": "ORT-03",
    "ward": "Orthopedics",
    "ward_id": 4,
    "floor": "First",
    "status": "occupied",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 26,
    "bed_number": "ORT-04",
    "ward": "Orthopedics",
    "ward_id": 4,
    "floor": "First",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 27,
    "bed_number": "ORT-05",
    "ward": "Orthopedics",
    "ward_id": 4,
    "floor": "First",
    "status": "cleaning",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 28,
    "bed_number": "MAT-01",
    "ward": "Maternity",
    "ward_id": 5,
    "floor": "Second",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 29,
    "bed_number": "MAT-02",
    "ward": "Maternity",
    "ward_id": 5,
    "floor": "Second",
    "status": "occupied",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 30,
    "bed_number": "MAT-03",
    "ward": "Maternity",
    "ward_id": 5,
    "floor": "Second",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 31,
    "bed_number": "MAT-04",
    "ward": "Maternity",
    "ward_id": 5,
    "floor": "Second",
    "status": "available",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  },
  {
    "id": 32,
    "bed_number": "MAT-05",
    "ward": "Maternity",
    "ward_id": 5,
    "floor": "Second",
    "status": "reserved",
    "patient_id": null,
    "patient_name": null,
    "bed_type": "general"
  }
];
