export const emergencyData = [
  {
    "id": 1,
    "patient_id": null,
    "patient_name": "Joseph Moore",
    "age": 55,
    "gender": "male",
    "chief_complaint": "Severe chest pain radiating to left arm, diaphoresis",
    "triage": "immediate",
    "bp_systolic": 90,
    "bp_diastolic": 60,
    "pulse": 110,
    "temperature": 37,
    "spo2": 92,
    "assigned_doctor_id": 3,
    "assigned_doctor_name": "Dr. Tariq Hussain",
    "status": "active",
    "disposition": null,
    "notes": "Suspected STEMI — cath lab on standby",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 2,
    "patient_id": null,
    "patient_name": "Rachel Green",
    "age": 28,
    "gender": "female",
    "chief_complaint": "Sudden onset thunderclap headache, vomiting x3",
    "triage": "very-urgent",
    "bp_systolic": 180,
    "bp_diastolic": 110,
    "pulse": 95,
    "temperature": 37.2,
    "spo2": 98,
    "assigned_doctor_id": null,
    "assigned_doctor_name": null,
    "status": "active",
    "disposition": null,
    "notes": "CT head ordered — SAH excluded",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 3,
    "patient_id": null,
    "patient_name": "James White",
    "age": 42,
    "gender": "male",
    "chief_complaint": "RTA — deep laceration left thigh, active bleeding",
    "triage": "urgent",
    "bp_systolic": 115,
    "bp_diastolic": 75,
    "pulse": 100,
    "temperature": 37.5,
    "spo2": 97,
    "assigned_doctor_id": 5,
    "assigned_doctor_name": "Dr. Bilal Ahmed",
    "status": "active",
    "disposition": null,
    "notes": "Wound irrigated, surgical consult",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 4,
    "patient_id": null,
    "patient_name": "Jessica Harris",
    "age": 35,
    "gender": "female",
    "chief_complaint": "Severe allergic reaction, facial swelling, urticaria",
    "triage": "immediate",
    "bp_systolic": 95,
    "bp_diastolic": 65,
    "pulse": 118,
    "temperature": 36.8,
    "spo2": 95,
    "assigned_doctor_id": 4,
    "assigned_doctor_name": "Dr. Nadia Omer",
    "status": "active",
    "disposition": null,
    "notes": "IV epinephrine given, anaphylaxis protocol",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 5,
    "patient_id": null,
    "patient_name": "Richard Martin",
    "age": 68,
    "gender": "male",
    "chief_complaint": "Acute confusion, slurred speech, right-sided weakness",
    "triage": "immediate",
    "bp_systolic": 170,
    "bp_diastolic": 100,
    "pulse": 88,
    "temperature": 36.5,
    "spo2": 96,
    "assigned_doctor_id": 7,
    "assigned_doctor_name": "Dr. Sana Yousuf",
    "status": "active",
    "disposition": null,
    "notes": "Stroke protocol activated, CT in progress",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 6,
    "patient_id": null,
    "patient_name": "Angela Clark",
    "age": 22,
    "gender": "female",
    "chief_complaint": "Severe abdominal pain, guarding, rebound tenderness",
    "triage": "urgent",
    "bp_systolic": 130,
    "bp_diastolic": 80,
    "pulse": 105,
    "temperature": 38.2,
    "spo2": 99,
    "assigned_doctor_id": 5,
    "assigned_doctor_name": "Dr. Bilal Ahmed",
    "status": "active",
    "disposition": null,
    "notes": "Surgical emergency evaluation",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  },
  {
    "id": 7,
    "patient_id": null,
    "patient_name": "Daniel Rodriguez",
    "age": 45,
    "gender": "male",
    "chief_complaint": "Difficulty breathing, wheeze, known asthmatic",
    "triage": "very-urgent",
    "bp_systolic": 135,
    "bp_diastolic": 88,
    "pulse": 115,
    "temperature": 37.1,
    "spo2": 88,
    "assigned_doctor_id": 4,
    "assigned_doctor_name": "Dr. Nadia Omer",
    "status": "admitted",
    "disposition": null,
    "notes": "Admitted to respiratory ward",
    "arrived_at": "2026-05-04T20:20:47.845Z",
    "resolved_at": null
  }
];
