export * from "./admissions";
export * from "./appointments";
export * from "./beds";
export * from "./emergency-cases";
export * from "./invoices";
export * from "./lab-orders";
export * from "./medications";
export * from "./patients";
export * from "./prescriptions";
