export const labOrdersData = [
  {
    "id": 1,
    "patient_id": 1,
    "patient_name": "Ahmad Hassan",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "test_name": "HbA1c",
    "test_code": "HBA1C",
    "category": "Biochemistry",
    "priority": "routine",
    "status": "completed",
    "result": "9.8",
    "normal_range": "4.0-5.6",
    "unit": "%",
    "result_notes": "Significantly elevated. Patient non-compliant.",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 2,
    "patient_id": 1,
    "patient_name": "Ahmad Hassan",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "test_name": "Fasting Blood Glucose",
    "test_code": "FBS",
    "category": "Biochemistry",
    "priority": "urgent",
    "status": "completed",
    "result": "248",
    "normal_range": "70-100",
    "unit": "mg/dL",
    "result_notes": null,
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 3,
    "patient_id": 1,
    "patient_name": "Ahmad Hassan",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "test_name": "Urine Microalbumin",
    "test_code": "MALB",
    "category": "Urinalysis",
    "priority": "routine",
    "status": "in-progress",
    "result": null,
    "normal_range": "<30",
    "unit": "mg/L",
    "result_notes": null,
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 4,
    "patient_id": 3,
    "patient_name": "Muhammad Ali",
    "doctor_id": 2,
    "doctor_name": "Dr. Amna Siddiqui",
    "consultation_id": null,
    "test_name": "Serum Creatinine",
    "test_code": "CREA",
    "category": "Biochemistry",
    "priority": "urgent",
    "status": "critical",
    "result": "4.2",
    "normal_range": "0.6-1.2",
    "unit": "mg/dL",
    "result_notes": "Critical level — nephrologist notified immediately",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 5,
    "patient_id": 3,
    "patient_name": "Muhammad Ali",
    "doctor_id": 2,
    "doctor_name": "Dr. Amna Siddiqui",
    "consultation_id": null,
    "test_name": "eGFR",
    "test_code": "EGFR",
    "category": "Biochemistry",
    "priority": "urgent",
    "status": "completed",
    "result": "18",
    "normal_range": ">60",
    "unit": "mL/min/1.73m²",
    "result_notes": "Stage 5 CKD range",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 6,
    "patient_id": 3,
    "patient_name": "Muhammad Ali",
    "doctor_id": 2,
    "doctor_name": "Dr. Amna Siddiqui",
    "consultation_id": null,
    "test_name": "Serum Potassium",
    "test_code": "K+",
    "category": "Biochemistry",
    "priority": "stat",
    "status": "critical",
    "result": "6.1",
    "normal_range": "3.5-5.0",
    "unit": "mEq/L",
    "result_notes": "Hyperkalemia — ECG ordered",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 7,
    "patient_id": 2,
    "patient_name": "Sara Khan",
    "doctor_id": 4,
    "doctor_name": "Dr. Nadia Omer",
    "consultation_id": null,
    "test_name": "Spirometry",
    "test_code": "SPIRO",
    "category": "Pulmonary",
    "priority": "routine",
    "status": "pending",
    "result": null,
    "normal_range": null,
    "unit": null,
    "result_notes": null,
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 8,
    "patient_id": 2,
    "patient_name": "Sara Khan",
    "doctor_id": 4,
    "doctor_name": "Dr. Nadia Omer",
    "consultation_id": null,
    "test_name": "Peak Flow Rate",
    "test_code": "PEFR",
    "category": "Pulmonary",
    "priority": "routine",
    "status": "completed",
    "result": "220",
    "normal_range": ">400",
    "unit": "L/min",
    "result_notes": "Severely reduced — acute exacerbation",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 9,
    "patient_id": 5,
    "patient_name": "Khalid Rehman",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "test_name": "Troponin I",
    "test_code": "TROP",
    "category": "Cardiac",
    "priority": "stat",
    "status": "completed",
    "result": "0.08",
    "normal_range": "<0.04",
    "unit": "ng/mL",
    "result_notes": "Elevated troponin — cardiology alerted",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 10,
    "patient_id": 5,
    "patient_name": "Khalid Rehman",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "test_name": "BNP",
    "test_code": "BNP",
    "category": "Cardiac",
    "priority": "urgent",
    "status": "completed",
    "result": "850",
    "normal_range": "<100",
    "unit": "pg/mL",
    "result_notes": "Elevated — heart failure suspected",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 11,
    "patient_id": 5,
    "patient_name": "Khalid Rehman",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "test_name": "ECG",
    "test_code": "ECG",
    "category": "Cardiology",
    "priority": "stat",
    "status": "completed",
    "result": "ST depression V4-V6",
    "normal_range": "Normal sinus rhythm",
    "unit": "",
    "result_notes": "ST changes consistent with NSTEMI",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  },
  {
    "id": 12,
    "patient_id": 4,
    "patient_name": "Ayesha Malik",
    "doctor_id": 5,
    "doctor_name": "Dr. Bilal Ahmed",
    "consultation_id": null,
    "test_name": "Complete Blood Count",
    "test_code": "CBC",
    "category": "Hematology",
    "priority": "routine",
    "status": "completed",
    "result": "WBC 9.2, Hb 12.8, Plt 245",
    "normal_range": "",
    "unit": "",
    "result_notes": "Within normal limits post-op",
    "ordered_at": "2026-05-04T20:20:27.774Z",
    "completed_at": null
  }
];
