export const prescriptionsData = [
  {
    "id": 1,
    "patient_id": 1,
    "patient_name": "David Johnson",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "drug_name": "Metformin",
    "dosage": "1000mg",
    "frequency": "Twice daily",
    "duration": "30 days",
    "route": "Oral",
    "instructions": "Take with meals",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 2,
    "patient_id": 1,
    "patient_name": "David Johnson",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "drug_name": "Glimepiride",
    "dosage": "4mg",
    "frequency": "Once daily (morning)",
    "duration": "30 days",
    "route": "Oral",
    "instructions": "Take before breakfast",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 3,
    "patient_id": 1,
    "patient_name": "David Johnson",
    "doctor_id": 1,
    "doctor_name": "Dr. Faisal Qureshi",
    "consultation_id": null,
    "drug_name": "Amlodipine",
    "dosage": "5mg",
    "frequency": "Once daily",
    "duration": "30 days",
    "route": "Oral",
    "instructions": "Take in the evening",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 4,
    "patient_id": 5,
    "patient_name": "Christopher Davis",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "drug_name": "Aspirin",
    "dosage": "75mg",
    "frequency": "Once daily",
    "duration": "90 days",
    "route": "Oral",
    "instructions": "Take after meals",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 5,
    "patient_id": 5,
    "patient_name": "Christopher Davis",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "drug_name": "Atorvastatin",
    "dosage": "40mg",
    "frequency": "Once at bedtime",
    "duration": "90 days",
    "route": "Oral",
    "instructions": "Take at night",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 6,
    "patient_id": 5,
    "patient_name": "Christopher Davis",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "drug_name": "Bisoprolol",
    "dosage": "5mg",
    "frequency": "Once daily",
    "duration": "90 days",
    "route": "Oral",
    "instructions": null,
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 7,
    "patient_id": 2,
    "patient_name": "Sarah Anderson",
    "doctor_id": 4,
    "doctor_name": "Dr. Nadia Omer",
    "consultation_id": null,
    "drug_name": "Salbutamol inhaler",
    "dosage": "2 puffs",
    "frequency": "Every 4-6 hrs PRN",
    "duration": "30 days",
    "route": "Inhalation",
    "instructions": "Shake well before use",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 8,
    "patient_id": 2,
    "patient_name": "Sarah Anderson",
    "doctor_id": 4,
    "doctor_name": "Dr. Nadia Omer",
    "consultation_id": null,
    "drug_name": "Fluticasone inhaler",
    "dosage": "250mcg",
    "frequency": "Twice daily",
    "duration": "30 days",
    "route": "Inhalation",
    "instructions": "Rinse mouth after use",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 9,
    "patient_id": 3,
    "patient_name": "Michael Brown",
    "doctor_id": 2,
    "doctor_name": "Dr. Amna Siddiqui",
    "consultation_id": null,
    "drug_name": "Furosemide",
    "dosage": "40mg",
    "frequency": "Twice daily",
    "duration": "14 days",
    "route": "Oral",
    "instructions": "Monitor potassium levels",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  },
  {
    "id": 10,
    "patient_id": 7,
    "patient_name": "William Miller",
    "doctor_id": 3,
    "doctor_name": "Dr. Tariq Hussain",
    "consultation_id": null,
    "drug_name": "Warfarin",
    "dosage": "5mg",
    "frequency": "Once daily",
    "duration": "90 days",
    "route": "Oral",
    "instructions": "INR monitoring required weekly",
    "status": "active",
    "created_at": "2026-05-04T20:20:58.243Z"
  }
];
